Repository Ditlog-Dev/ditlog-webservice, pull requests merged in 2018-03, with the labels that each got.

#2 Docker with CI integration ready
  .gitignore
  .travis.yml
  Dockerfile
  application.properties.sample
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  init
  src/main/java/id/ac/itb/logistik/ditlog/DitlogApplication.java
  src/main/java/id/ac/itb/logistik/ditlog/repository/IndicatorRepository.java
  src/main/properties/.gitkeep
  src/test/java/id/ac/itb/logistik/ditlog/DitlogApplicationTests.java
  start
  test
Labels: enhancement

#4 [WIP] Fix bugs in test file
  test
Labels: bug

#6 Done : fixing bugs, add indicator, pagination
  .gitignore
  .travis.yml
  Dockerfile
  README.md
  application.properties.sample
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  init
  src/main/java/id/ac/itb/logistik/ditlog/DitlogApplication.java
  src/main/java/id/ac/itb/logistik/ditlog/controller/IndicatorController.java
  src/main/java/id/ac/itb/logistik/ditlog/model/Indicator.java
  src/main/java/id/ac/itb/logistik/ditlog/repository/IndicatorRepository.java
  src/main/resources/.gitkeep
  src/test/java/id/ac/itb/logistik/ditlog/DitlogApplicationTests.java
  src/test/resources/.gitkeep
  start
  test
  test.properties.sample
Labels: enhancement

#3 Features/i6 login
  README.md
  application.properties.sample
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  init
  src/main/java/id/ac/itb/logistik/ditlog/DitlogApplication.java
  src/main/java/id/ac/itb/logistik/ditlog/config/JwtFilter.java
  src/main/java/id/ac/itb/logistik/ditlog/controller/IndicatorController.java
  src/main/java/id/ac/itb/logistik/ditlog/controller/UserController.java
  src/main/java/id/ac/itb/logistik/ditlog/model/BaseResponse.java
  src/main/java/id/ac/itb/logistik/ditlog/model/Indicator.java
  src/main/java/id/ac/itb/logistik/ditlog/model/User.java
  src/main/java/id/ac/itb/logistik/ditlog/model/UserPayload.java
  src/main/java/id/ac/itb/logistik/ditlog/repository/IndicatorRepository.java
  src/main/java/id/ac/itb/logistik/ditlog/repository/UserRepository.java
  src/main/resources/.gitkeep
  src/test/java/id/ac/itb/logistik/ditlog/DitlogApplicationTests.java
  src/test/java/id/ac/itb/logistik/ditlog/DitlogUserServiceTests.java
  src/test/resources/.gitkeep
  test
  test.properties.sample
Labels: enhancement

#8 [Done] Post indicator fixes
  README.md
  src/main/java/id/ac/itb/logistik/ditlog/DitlogApplication.java
  src/main/java/id/ac/itb/logistik/ditlog/controller/ErrorHandler.java
  src/main/java/id/ac/itb/logistik/ditlog/controller/IndicatorController.java
  src/main/java/id/ac/itb/logistik/ditlog/model/BaseResponse.java
  src/main/java/id/ac/itb/logistik/ditlog/model/Indicator.java
  src/main/java/id/ac/itb/logistik/ditlog/repository/IndicatorRepository.java
  src/test/java/id/ac/itb/logistik/ditlog/BaseTest.java
  src/test/java/id/ac/itb/logistik/ditlog/DitlogApplicationTests.java
  src/test/java/id/ac/itb/logistik/ditlog/DitlogIndicatorTests.java
Labels: enhancement

#9 [FIX] fix gradle redownload and bug in docker-compose test
  Dockerfile
  build.gradle
  docker-compose.yml
  start
  test
Labels: bug, enhancement

#10 [FIX] gradle redownload and bug in docker-compose test
  Dockerfile
  build.gradle
  docker-compose.yml
  start
  test
Labels: bug, enhancement
